import { z } from "zod";

const key = z.string().trim().min(8).max(180);
const id = z.uuid();
const optionalId = id.nullable().default(null);
const optionalDateTime = z.iso.datetime({ offset: true }).nullable().default(null);

export const businessActionSchema = z.discriminatedUnion("action", [
  z.object({ action: z.literal("create_client"), payload: z.object({ name: z.string().trim().min(1).max(160), company: z.string().trim().max(160).default(""), email: z.email().or(z.literal("")).default(""), phone: z.string().trim().max(40).default(""), status: z.enum(["lead","active","paused","former"]).default("lead"), health: z.enum(["on_track","at_risk","blocked"]).default("on_track"), next_action: z.string().trim().max(240).default(""), next_action_at: optionalDateTime }).strict(), idempotency_key: key }).strict(),
  z.object({ action: z.literal("update_client"), payload: z.object({ id, name: z.string().trim().min(1).max(160).optional(), company: z.string().trim().max(160).optional(), email: z.email().or(z.literal("")).optional(), phone: z.string().trim().max(40).optional(), status: z.enum(["lead","active","paused","former"]).optional(), health: z.enum(["on_track","at_risk","blocked"]).optional(), next_action: z.string().trim().max(240).optional(), next_action_at: z.iso.datetime({ offset: true }).nullable().optional() }).strict(), expected_version: z.number().int().positive(), idempotency_key: key }).strict(),
  z.object({ action: z.literal("add_client_contact"), payload: z.object({ client_id: id, name: z.string().trim().min(1).max(160), role: z.string().trim().max(120).default(""), email: z.email().or(z.literal("")).default(""), phone: z.string().trim().max(40).default(""), is_primary: z.boolean().default(false) }).strict(), idempotency_key: key }).strict(),
  z.object({ action: z.literal("add_client_note"), payload: z.object({ client_id: id, note: z.string().trim().min(1).max(4000) }).strict(), idempotency_key: key }).strict(),
  z.object({ action: z.literal("create_deliverable"), payload: z.object({ client_id: optionalId, project_id: optionalId, title: z.string().trim().min(1).max(220), description: z.string().trim().max(1200).default(""), status: z.enum(["planned","in_progress","review","completed","blocked"]).default("planned"), progress: z.number().int().min(0).max(100).default(0), due_at: optionalDateTime }).strict(), idempotency_key: key }).strict(),
  z.object({ action: z.literal("create_proposal"), payload: z.object({ client_id: optionalId, project_id: optionalId, title: z.string().trim().min(1).max(220), status: z.enum(["draft","sent","accepted","rejected","expired"]).default("draft"), amount: z.number().min(0).max(100_000_000), currency: z.string().length(3).default("INR"), valid_until: z.iso.date().nullable().default(null), notes: z.string().trim().max(2000).default("") }).strict(), idempotency_key: key }).strict(),
  z.object({ action: z.literal("create_invoice"), payload: z.object({ client_id: optionalId, project_id: optionalId, invoice_number: z.string().trim().min(1).max(40), status: z.enum(["draft","sent","partial","paid","overdue","cancelled"]).default("draft"), issued_on: z.iso.date(), due_on: z.iso.date().nullable().default(null), subtotal: z.number().min(0).max(100_000_000), tax: z.number().min(0).max(100_000_000).default(0), currency: z.string().length(3).default("INR"), notes: z.string().trim().max(2000).default("") }).strict(), idempotency_key: key }).strict(),
  z.object({ action: z.literal("record_payment"), payload: z.object({ invoice_id: id, amount: z.number().positive().max(100_000_000), paid_at: z.iso.datetime({ offset: true }), method: z.string().trim().min(1).max(80).default("bank_transfer"), reference: z.string().trim().max(120).default(""), note: z.string().trim().max(500).default("") }).strict(), idempotency_key: key }).strict(),
  z.object({ action: z.literal("add_transaction"), payload: z.object({ entry_type: z.enum(["income","expense"]), entry_date: z.iso.date(), amount: z.number().positive().max(100_000_000), currency: z.string().length(3).default("INR"), category: z.string().trim().min(1).max(120), description: z.string().trim().max(500).default(""), client_id: optionalId, project_id: optionalId, invoice_id: optionalId, recurring: z.boolean().default(false) }).strict(), idempotency_key: key }).strict(),
  z.object({ action: z.literal("create_lead"), payload: z.object({ name: z.string().trim().min(1).max(160), company: z.string().trim().max(160).default(""), email: z.email().or(z.literal("")).default(""), status: z.enum(["new","contacted","qualified","proposal","won","lost"]).default("new"), estimated_value: z.number().min(0).max(100_000_000).default(0), probability: z.number().int().min(0).max(100).default(10), next_action: z.string().trim().max(240).default(""), next_action_at: optionalDateTime }).strict(), idempotency_key: key }).strict(),
  z.object({ action: z.literal("create_business_goal"), payload: z.object({ title: z.string().trim().min(1).max(220), target_value: z.number(), current_value: z.number().default(0), unit: z.string().trim().max(40).default(""), deadline: z.iso.date().nullable().default(null) }).strict(), idempotency_key: key }).strict(),
  z.object({ action: z.literal("create_recurring_operation"), payload: z.object({ title: z.string().trim().min(1).max(220), cadence: z.enum(["daily","weekly","monthly","quarterly"]), next_due: z.iso.date() }).strict(), idempotency_key: key }).strict(),
  z.object({ action: z.literal("create_financial_goal"), payload: z.object({ title: z.string().trim().min(1).max(220), target_amount: z.number().positive(), current_amount: z.number().min(0).default(0), currency: z.string().length(3).default("INR"), deadline: z.iso.date().nullable().default(null) }).strict(), idempotency_key: key }).strict(),
]);

export type BusinessActionInput = z.infer<typeof businessActionSchema>;
