import { z } from "zod";

const id=z.uuid();const key=z.string().trim().min(8).max(180);const date=z.iso.date();const dateTime=z.iso.datetime({offset:true});
export const learningActionSchema=z.discriminatedUnion("action",[
  z.object({action:z.literal("create_skill"),payload:z.object({name:z.string().trim().min(1).max(140),category:z.string().trim().max(80).default("General"),status:z.enum(["planned","active","paused","completed"]).default("active"),mastery:z.number().int().min(0).max(100).default(0),target:z.string().trim().max(500).default(""),deadline:date.nullable().default(null)}).strict(),idempotency_key:key}).strict(),
  z.object({action:z.literal("log_learning_session"),payload:z.object({skill_id:id,topic_id:id.nullable().default(null),started_at:dateTime,ended_at:dateTime.nullable().default(null),duration_minutes:z.number().int().min(1).max(1440),notes:z.string().trim().max(2000).default(""),evidence_url:z.url().or(z.literal("")).default("")}).strict(),idempotency_key:key}).strict(),
  z.object({action:z.literal("update_learning_topic"),payload:z.object({id,status:z.enum(["not_started","learning","practicing","mastered"]).optional(),confidence:z.number().min(0).max(5).optional(),mastery:z.number().int().min(0).max(100).optional(),last_revised_at:dateTime.nullable().optional(),next_revision_on:date.nullable().optional(),weak:z.boolean().optional()}).strict(),expected_version:z.number().int().positive(),idempotency_key:key}).strict(),
  z.object({action:z.literal("record_dsa_problem"),payload:z.object({platform:z.string().trim().min(1).max(40).default("leetcode"),external_id:z.string().trim().min(1).max(160),title:z.string().trim().min(1).max(220),difficulty:z.enum(["easy","medium","hard"]),solved_at:dateTime,confidence:z.number().min(0).max(5).default(3),notes:z.string().trim().max(2000).default(""),url:z.url().or(z.literal("")).default(""),topic_ids:z.array(id).max(10).default([])}).strict(),idempotency_key:key}).strict(),
  z.object({action:z.literal("create_course"),payload:z.object({skill_id:id.nullable().default(null),title:z.string().trim().min(1).max(220),provider:z.string().trim().max(140).default(""),status:z.enum(["planned","active","paused","completed"]).default("active"),progress:z.number().int().min(0).max(100).default(0),certificate_url:z.url().or(z.literal("")).default(""),started_on:date.nullable().default(null)}).strict(),idempotency_key:key}).strict(),
  z.object({action:z.literal("create_learning_goal"),payload:z.object({skill_id:id.nullable().default(null),title:z.string().trim().min(1).max(220),target_value:z.number(),current_value:z.number().default(0),unit:z.string().trim().max(40).default(""),deadline:date.nullable().default(null)}).strict(),idempotency_key:key}).strict(),
  z.object({action:z.literal("create_subject"),payload:z.object({semester_id:id,faculty_id:id.nullable().default(null),code:z.string().trim().min(1).max(20),name:z.string().trim().min(1).max(180),credits:z.number().min(0).max(30).default(3),attendance_target:z.number().min(0).max(100).default(75),syllabus_progress:z.number().int().min(0).max(100).default(0),color:z.string().trim().max(30).default("blue")}).strict(),idempotency_key:key}).strict(),
  z.object({action:z.literal("log_attendance"),payload:z.object({subject_id:id,class_date:date,status:z.enum(["present","absent","late","excused"]),note:z.string().trim().max(500).default("")}).strict(),idempotency_key:key}).strict(),
  z.object({action:z.literal("create_assignment"),payload:z.object({subject_id:id,title:z.string().trim().min(1).max(220),description:z.string().trim().max(2000).default(""),status:z.enum(["not_started","in_progress","submitted","graded"]).default("not_started"),due_at:dateTime.nullable().default(null)}).strict(),idempotency_key:key}).strict(),
  z.object({action:z.literal("create_exam"),payload:z.object({subject_id:id,title:z.string().trim().min(1).max(220),exam_type:z.string().trim().max(80).default("internal"),starts_at:dateTime,duration_minutes:z.number().int().min(1).max(720).default(90),weight:z.number().min(0).max(100).default(0),syllabus_progress:z.number().int().min(0).max(100).default(0)}).strict(),idempotency_key:key}).strict(),
  z.object({action:z.literal("update_academic_topic"),payload:z.object({id,status:z.enum(["not_started","learning","practicing","mastered"]).optional(),progress:z.number().int().min(0).max(100).optional(),priority:z.enum(["low","medium","high","critical"]).optional()}).strict(),expected_version:z.number().int().positive(),idempotency_key:key}).strict(),
]);
